Add Mark all read Button
PDFTron/webviewer-collab-advanced-sample pull request #7
Opened 2021-03-02 10:50 UTC by jiaqihuang-233

1. Add a mark all as read button
2. Show error when invitations fail

2021-03-02 15:13 UTC, lbittner-pdftron requested changes

2021-03-02 15:13 UTC, lbittner-pdftron commented on client/components/InviteModal/InviteModal.tsx
> +  let success = true;
Hey Jackie, this is not a good way to do this as every time this function is rendered this variable will be reset to `true`. Use a ref or state instead

2021-03-02 15:13 UTC, lbittner-pdftron commented on client/components/InviteModal/InviteModal.tsx
> +      }
You shouldn't be relying on the `permissionError` callback to check if this worked. Doesn't `inviteUsersToDocument` throw an error if there are no permissions?

2021-03-02 22:14 UTC, jiaqihuang-233 commented on client/components/InviteModal/InviteModal.tsx
> +      }
Hey @logan, no it doesn't. It only has this line `this.trigger('permissionError', 'Document', 'invite');` in the catch block.

2021-03-02 22:18 UTC, lbittner-pdftron commented on client/components/InviteModal/InviteModal.tsx
> +      }
Ok, I think we should fix that to actually throw an error then

2021-03-11 20:42 UTC, lbittner-pdftron approved these changes

2021-03-11 20:42 UTC, merged